name: Generate Contributions

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: Sukhman3125
          options: theme=tokyo-night&hide_border=true&area=true&radius=8
          output_path: graph-dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Sukhman3125
          outputs: |
            snake-dist/github-contribution-grid-snake.svg
            snake-dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Combine generated files
        run: |
          mkdir -p dist

          cp graph-dist/activity-graph.svg dist/activity-graph.svg
          cp snake-dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.svg
          cp snake-dist/github-contribution-grid-snake-dark.svg dist/github-contribution-grid-snake-dark.svg

      - name: Publish contributions
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
